spring:
  application:
    name: springBootSecurity
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: ${BD_URL}
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # en prod: validate o flyway/liquibase
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope: public_profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Facebook
#      provider:
        # Google usa el default de Spring (no hace falta proveedor custom)
        # Facebook: Spring trae defaults razonables, no suele hacer falta tocar.
#      resourceserver:
#        jwt:
        # Si además validas *tu* JWT RS256 en /api/**, mantén tu verificación como ya la tienes.
        # Si usas tu JwtService con RSA, no pongas issuer-uri aquí (ya lo gestionas tú).
        # Deja esta sección si también aceptas Bearer externos; si no, puedes omitirla.
        # issuer-uri: (OPCIONAL si validas tokens externos)
        # jwk-set-uri: (OPCIONAL)

security:
  jwt:
    issuer: "springbootsecurity"
    access:
      minutes: 15
    refresh:
      days: 7
    rsa:
      public-key: file:${PUBLIC_KEY}
      private-key: file:${SECRET_KEY}

logging:
  level:
    org.springframework.security: INFO

server:
  port: 8080

---
# perfil para test
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  h2:
    console:
      enabled: true
      path: /h2-console