spring:
  application:
    name: springBootSecurity
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: ${BD_URL}
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # en prod: validate o flyway/liquibase
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: INFO

server:
  port: 8080

---
# perfil para test
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  h2:
    console:
      enabled: true
      path: /h2-console